## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - windows
  # - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
 apt: # apt-get for linux
   packages:
   - libgtk-3-dev

script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')  
  - git clone https://github.com/sisl/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "SISL"))')  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia --project --color=yes -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'  
  - julia --project --color=yes -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'  
