## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
git:
  depth: 99999999

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/sisl/Vec.jl"))'
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/sisl/Records.jl"))'
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/sisl/AutomotiveDrivingModels.jl"))'
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/sisl/AutoViz.jl"))'
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.build("AutomotiveSensors"); Pkg.test("AutomotiveSensors"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("AutomotiveSensors")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AutomotiveSensors")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
